name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: read  # Allow read access to repository contents
  packages: write # Allow write access to publish packages

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you want to use
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npx eslint . --config eslint.config.js # Specify the config file if needed

      - name: Run tests
        run: npm test # Adjust this if you have a specific test command

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use a secret for your npm token
